import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "@styles/globals.css";
import Header from "@components/Header";

const splineSans = Spline_Sans({
  variable: "--font-spline-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${splineSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
